language: java
jdk:
- oraclejdk8
before_install:
- pip install --user codecov
after_success:
- codecov
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
before_deploy:
- "./gradlew releaseZip"
deploy:
  provider: releases
  api_key: 
  secure: "Az3mWI7pDjxWa85O/ZuScsKVQMnB91J13xEZo41g+dzutRSEWVVLwKD1LlhMY9lOttcIw9WkSkVg5LZOVgeJxO0MgQHJ4GEPJkwtPoavcPKGYCppcOC3tIGOyX1i4uWjPORyha0WYQhyls1Zz2k/pthnNM6brSzJVH0+m4mM++THSn0fC4TfxF8rrtANvkMleYIrMIBW7VFGlygSM3ALlaVULSPdGhcxlTKJcOnKDSd3KBfShP3zb0++GLfJYp1MmTw+OHxJwHNreWjyTYlzE+8HEN8RGdFmp4tly8o3WiyuIVgHGQH5wGhKjBKn03zabyuN8nxqb023BzqWFugmiEWzAiVzLlv+C9vBryF6mkkrH/y9tyUJZxgrUMplOd1J+ZSo4wHAaeBBBv3E98xFGm7C3GDoRLWL5zcMkZpoSa6mAtUp1BOjnekT5fuEBJF4eVbCSCmTTGiB+EyO/Pc2NzUUduvBEpw2IPG37J2+bfrBk0mnBB1AO+iw6VDOIGSVcMamzQ80bNKoJZNj60J9DWP0iSZFkBQKTqIIlNv3B4eGxsHloVNLortkh32+5ke6nx2CKyaGIlQlyQNOudNuChsnBiJ0Ut/lzDhdnq0C3MGv62c0CaCuF+QZX+1EoSp0YTWHbdLfd1VgozISPFyWmJ8p2EQaBwNKjrtSSQxS5gc="
  app: ksiazekm-jaa-submissions
  on:
    repo: ksiazekm/JAlgoArena-Submissions
