language: java
jdk:
- oraclejdk8
before_install:
- pip install --user codecov
after_success:
- codecov
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
before_deploy:
- "./gradlew releaseZip"
deploy:
  provider: heroku
  api_key: 
   secure: "ikLAiOxwlpp7VjPxrSO/eidGi4OudM3ruO9SKj9Uc36ty/Z3Q34DywGju3R/mVLuxNYtJMwgouexdQHNPIcWf7Sl3obFEi9Nmehlzv1Gv8Ro0/JjXgIXhnsa97mFdiS8lQoN7TSF8P5XAaf0udjnrbENcZDsvZA70O5T66Q1scOLVUpaABCuml5y64qd2e+0wIGJKs5zUU7AEVJvKqlu9HoV55+H2S3vxjEzJeWpMLihunuQGx+8aDAAm/SbSqZVY1e9eDI7rTf7ySZY6Smoikdbyqbg3qd1r4BDBEBp5rZY62cq7SyWI4HuNGKkY9rOCAMWPWMKtxhgQ4VRUubpe2ZKWq0+WzsAieSD41cu2hJ2DjiKFXY25d5Lc8L9S4+/G9DFCwEOXlumWXIEcJDUvBUbL+P5tEn6AYvPYhSc74/TpRHDMlpAhcgoHxSZZLxzxmddnBW9FwqiMrmBUUPqg2+9U6L/cRSDbZn5t7msbqywi74vld/SrvILwLbR9RbBxL8xn6oXFU6HcDkLCHxMkmD3AalauGCZV8hEtiQvfbTonm4iPKLeYQpcMg2QMSKDFyWpJ4sOf9WbqoxbBhwuDjzKULNc80cu4l+TV+O+ZA2uWL1uyjr4trP4d8yVKDJqHuLy1prT8lJV7x8IEyy4VH4p3hQHOjlZf4GRZJCXJwM=" 
 app: ksiazekm-jaa-submissions
  on:
    repo: ksiazekm/JAlgoArena-Submissions
