language: java
jdk:
- oraclejdk8
before_install:
- pip install --user codecov
after_success:
- codecov
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
before_deploy:
- "./gradlew releaseZip"
deploy:
  provider: heroku
  api_key: 
   secure: "iOH61VG0YpOOThV8AMuFA0BY88r5IVT4HSaykYcGSqLtGXAT0uNChv2nbZ0JQwyBA+Zl3Ij6GQiXfR9DjoX44T1nEl0fFGpin301vxjR5NRjjpBZFhutJM+f3oJbLyqAdGdU5cvl6wsHC4IeSce0XnBh/zlj/tZ5CvCHI+reABnpTekB4iiEd/MloZNc2ALz+tXfWnd4TzqSn955FJi+wO/Bf/+iwdRLzTQ5YMEAmJSogaNxeCezcQLCm0RhI5Yor3z0XnJ4R10iyBJSmlhyhRp4GXIcDgXpb/5fG11DIKssD6hFcpAHM0Opi58FRY276fAb/XEgy23NV8UROw/pLROo1luiWJkYQKbJrZ9RCQSd1SmcxX7edBmO8/ZeK585Q7duvbCFSrpsmcXKvbu46Yb/3zNlMbGFCki5u7sFEl4AP3LZI7AcDIEUnRNB1dFx16PROBAB4488qswsbFMxAKCPlSJ+0AyHO7Bg3ZLMJV4sfPoYZIi/Qsh5f+1T/UJ5Ga1OUpJn+FpR6M3MXJb83w3XJY0Xl0v6jYExB3gM1jw1WjBqIuLQzA8sUYAewIL7Sh5PkMo9u/nuSc6aQvIGgh+snTN7hVkMY48Vg3Xxbn7KdanMP8cqkNwBVt+1ve5rbF76q63mCYlgAa6CxD2LWWJ1vy2L+6pt+cJhFSyprTk="
 app: ksiazekm-jaa-submissions
 on:
    repo: ksiazekm/JAlgoArena-Submissions
