language: java
jdk:
- oraclejdk8
before_install:
- pip install --user codecov
after_success:
- codecov
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
before_deploy:
- "./gradlew releaseZip"
deploy:
  provider: releases
  api_key: 
   secure: "cvVlvkiX17UdUbylgM+akJwb9xrlYOUU32clTxRTy7g4TIDgkpV+w5LII5EUd+WdrUiHU8izpvnmIvPrlsKXrJil4EgugRh4jgWj+kjH+egopYHsi2e6XlmDmwEdoOUBNtvMYfGImLB4DI+wcKmpKGnpo2AuWpLc8DlCcMmkoLF6JcWlItBg6ic5KLLiO0XybqUzBcuV3PRC7s7kpfHFgdcJZ33cSZhsnUHcw4x+4ZlwRkpfITTOK7zcaaljqMU0nLBAeyKeZW2a11XY4pLIrN3XvuDV/tG0qXk9ZUAzg0yx4H+kYITI9jjOupMsyE/2JeO223dTJqjr1qns6SZ+o0hWISuFaUoe4B5S5zygfW7Xqg/4Hj6xKbBtSw8IM56A1sTFU0CffWS6NYgturzrb51CVOH2RfBj8k/YdSp5MZC/cUqZHTp+jHHivEsxBig3yvQ4IC7qMeVWb7gvQyjTL7xSXZFbc4PXsKGmahgg2pGIld23lSqUnvwSIMv9hZeT5nEgaCsWK5wV3bsTciwAFUqWE5zz/36ctx/GF025vKubQKVz+Y1tfhjBIairKiLyrt9X4qLYYjJu7phczzBP+/5Z3E/OJzrK9qkNcOeO4mgBdtvDl43LBXG/rQkfzBs4G0cJkm+lASrJzA6Ofv6CZonGFZqf5UcsaZJLM0y6Mtg="
  app: ksiazekm-jaa-submissions
  on:
    repo: ksiazekm/JAlgoArena-Submissions
